seed: 42

dataset:
  train_csv: dummy_train.csv
  val_csv: dummy_val.csv
  num_classes: 2

model:
  name: resnet18

training:
  batch_size: 2
  lr: 0.001
  epochs: 1

wandb:
  project: "dummy_test"
  entity: "your_wandb_entity"
  use: false
